### ISSUE TITLE
Error: 'list' value has no field or method '_values'  on lib/new_sets.bzl

### ISSUE THREAD

**Issue by uajith** [bazelbuild/bazel-skylib#315]
On Bazel 4.0 I am getting the below error:
```
ERROR: /home/ajithu/.cache/bazel/_bazel_ajithu/64f281071d7b4d7bf8c57a82ac06e780/external/io_bazel_rules_go/go/tools/coverdata/BUILD.bazel:3:16: in go_tool_library rule @io_bazel_rules_go//go/tools/coverdata:coverdata: 
Traceback (most recent call last):
	File "/home/ajithu/.cache/bazel/_bazel_ajithu/64f281071d7b4d7bf8c57a82ac06e780/external/io_bazel_rules_go/go/private/rules/library.bzl", line 42, column 25, in _go_library_impl
		archive = go.archive(go, source)
	File "/home/ajithu/.cache/bazel/_bazel_ajithu/64f281071d7b4d7bf8c57a82ac06e780/external/io_bazel_rules_go/go/private/actions/archive.bzl", line 219, column 29, in emit_archive
		cgo_exports = sets.union(cgo_exports, *[a.cgo_exports for a in direct])
	File "/home/ajithu/.cache/bazel/_bazel_ajithu/64f281071d7b4d7bf8c57a82ac06e780/external/bazel_skylib/lib/new_sets.bzl", line 189, column 42, in _union
		return struct(_values = dicts.add(*[s._values for s in args]))
Error: 'list' value has no field or method '_values'
ERROR: Analysis of target '//tools/cedp_ci:cedp_ci' failed; build aborted: Analysis of target '@io_bazel_rules_go//go/tools/coverdata:coverdata' failed
```
It is seen that the problem is [here](https://github.com/bazelbuild/bazel-skylib/blob/main/lib/new_sets.bzl#L190):  

This is my WORKSPACE change:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "bazel_skylib",
    url = "https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.1/bazel-skylib-1.0.1.tar.gz",
    sha256 = "f1c8360c01fcf276778d3519394805dc2a71a64274a3a0908bc9edff7b5aebc8",
)
load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")
bazel_skylib_workspace()
```

**Comment by uajith** [comment]
This works fine, Only thing we need to consider is the order in the WORKSPACE file.
those should be defined on top of io_bazel_rules_jsonnet
