### ISSUE TITLE
Bazel skylib fails on Bazel@HEAD in downstream CI

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel-skylib#446]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2997#0187e486-1edf-42e5-9753-4bc1c73bdd2f

Platform : Bazel skylib (Latest Bazel on :windows: (OpenJDK 11, VS2019))

Logs:
```
ERROR: An error occurred during the fetch of repository 'com_github_pelletier_go_toml':
  | Traceback (most recent call last):
  | File "C:/b/uyqoagsk/external/bazel_gazelle/internal/go_repository.bzl", line 230, column 17, in _go_repository_impl
  | fail("failed to fetch %s: %s" % (ctx.name, result.stderr))
  | Error in fail: failed to fetch com_github_pelletier_go_toml: fetch_repo: github.com/pelletier/go-toml@v1.9.5: Get "https://proxy.golang.org/github.com/pelletier/go-toml/@v/v1.9.5.info": net/http: TLS handshake timeout
  | (02:16:19) ERROR: C:/b/bk-windows-p38h/bazel-downstream-projects/bazel-skylib/WORKSPACE:25:34: fetching go_repository rule //external:com_github_pelletier_go_toml: Traceback (most recent call last):
  | File "C:/b/uyqoagsk/external/bazel_gazelle/internal/go_repository.bzl", line 230, column 17, in _go_repository_impl
  | fail("failed to fetch %s: %s" % (ctx.name, result.stderr))
  | Error in fail: failed to fetch com_github_pelletier_go_toml: fetch_repo: github.com/pelletier/go-toml@v1.9.5: Get "https://proxy.golang.org/github.com/pelletier/go-toml/@v/v1.9.5.info": net/http: TLS handshake timeout
  | (02:16:19) ERROR: C:/b/uyqoagsk/external/bazel_gazelle/language/go/BUILD.bazel:15:11: @bazel_gazelle//language/go:go depends on @com_github_pelletier_go_toml//:go-toml in repository @com_github_pelletier_go_toml which failed to fetch. no such package '@com_github_pelletier_go_toml//': failed to fetch com_github_pelletier_go_toml: fetch_repo: github.com/pelletier/go-toml@v1.9.5: Get "https://proxy.golang.org/github.com/pelletier/go-toml/@v/v1.9.5.info": net/http: TLS handshake timeout
  | (02:16:19) ERROR: Analysis of target '@bazel_skylib_gazelle_plugin//bzl:gazelle-skylib' failed; build aborted:
 
```

Steps followed :  

1. https://github.com/bazelbuild/bazel-skylib.git
2. git reset 2f0bb4cec0297bb38f830a72fa8961bee057c3cd --hard
3. export USE_BAZEL_VERSION=8087520b153832656695fef6f3654ed432642c98
4. bazel build @bazel_skylib_gazelle_plugin//...

CC @meteorcloudy

**Comment by meteorcloudy** [comment]
Might be a network flake, rerunning at https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2997#0187e5db-c4e0-4ce5-b9bd-922c49ee3b9c

**Comment by meteorcloudy** [comment]
Rerun succeeded, closing the issue
