### ISSUE TITLE
 ERROR: no such package '@@rules_java~7.1.0~toolchains~remote_java_tools with BAZEL@HEAD

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel-skylib#477]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3461#018bd123-7d0a-42a4-959d-acde9743b703

Platform : Windows

Logs:

```
java.io.IOException: java.lang.InterruptedException
    at com.google.devtools.build.lib.remote.ReferenceCountedChannel.getServerCapabilities(ReferenceCountedChannel.java:86)
    at com.google.devtools.build.lib.remote.GrpcCacheClient.getCacheCapabilities(GrpcCacheClient.java:266)
    at com.google.devtools.build.lib.remote.RemoteCache.getCacheCapabilities(RemoteCache.java:100)
    at com.google.devtools.build.lib.remote.RemoteExecutionService.lambda$buildUploadManifestAsync$6(RemoteExecutionService.java:1345)
    at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
    at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
    at io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3644)
    at com.google.devtools.build.lib.remote.RemoteExecutionService.buildUploadManifest(RemoteExecutionService.java:1363)
    at com.google.devtools.build.lib.remote.RemoteExecutionService.uploadOutputs(RemoteExecutionService.java:1418)
    at com.google.devtools.build.lib.remote.RemoteSpawnCache$1.store(RemoteSpawnCache.java:193)
    at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:165)
    at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:119)
    at com.google.devtools.build.lib.exec.SpawnStrategyResolver.exec(SpawnStrategyResolver.java:45)
    at com.google.devtools.build.lib.exec.StandaloneTestStrategy.runTestAttempt(StandaloneTestStrategy.java:839)
    at com.google.devtools.build.lib.exec.StandaloneTestStrategy.beginTestAttempt(StandaloneTestStrategy.java:315)
    at com.google.devtools.build.lib.exec.StandaloneTestStrategy$StandaloneTestRunnerSpawn.execute(StandaloneTestStrategy.java:581)
    at com.google.devtools.build.lib.analysis.test.TestRunnerAction.executeAllAttempts(TestRunnerAction.java:1163)
    at com.google.devtools.build.lib.analysis.test.TestRunnerAction.execute(TestRunnerAction.java:975)
    at com.google.devtools.build.lib.analysis.test.TestRunnerAction.execute(TestRunnerAction.java:952)
    at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.executeAction(SkyframeActionExecutor.java:1154)
    at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1071)
    at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:165)
    at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:94)
    at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:568)
    at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:860)
    at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:334)
    at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:172)
    at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:461)
    at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:414)
    at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.InterruptedException
    at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
    at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:111)
    at com.google.devtools.build.lib.remote.ReferenceCountedChannel.blockingGet(ReferenceCountedChannel.java:135)
    at com.google.devtools.build.lib.remote.ReferenceCountedChannel.getServerCapabilities(ReferenceCountedChannel.java:79)
    ... 34 more


(02:08:31) ERROR: no such package '@@rules_java~7.1.0~toolchains~remote_java_tools//': C:/b/4z2pcm55/external/rules_java~7.1.0~toolchains~remote_java_tools/java_tools/JavaBuilder_deploy.jar (Permission denied)
(02:08:31) ERROR: C:/b/4z2pcm55/external/rules_java~7.1.0/toolchains/BUILD:243:27: @@rules_java~7.1.0//toolchains:toolchain_java8 depends on @@rules_java~7.1.0~toolchains~remote_java_tools//:GenClass in repository @@rules_java~7.1.0~toolchains~remote_java_tools which failed to fetch. no such package '@@rules_java~7.1.0~toolchains~remote_java_tools//': C:/b/4z2pcm55/external/rules_java~7.1.0~toolchains~remote_java_tools/java_tools/JavaBuilder_deploy.jar (Permission denied)
(02:08:31) ERROR: Analysis of target '//docs:docs_subpackages_doc-difftest' failed; build aborted: Analysis failed
```

Steps:

```
git clone https://github.com/bazelbuild/bazel-skylib.git
git reset 9c9beee7411744869300f67a98d42f5081e62ab3 --hard
export USE_BAZEL_VERSION=dfcb9efc255535103d75981536112df3fd1993db
bazel test -- //... @bazel_skylib_gazelle_plugin//...
```

CC Greenteam @SalmaSamy

**Comment by sgowroji** [comment]
Hi @[c-parsons](https://github.com/c-parsons), Can you take a look at the above issue. Thanks!

**Comment by sgowroji** [comment]
CI looks green for Bazel skylib. Hence closing this issue.
