### ISSUE TITLE
[Bazel ci]Error no native function or rules 'sh_binary'


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel-skylib#547]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4198#01928934-370b-445d-a0f4-65e1ce9d1213

 Platform: Ubuntu

 Logs: 
```
ERROR: Traceback (most recent call last):
	File "/var/lib/buildkite-agent/builds/bk-docker-ms75/bazel-org-repo-root/bazel-skylib/docs/BUILD", line 182, column 12, in <toplevel>
		update_docs(
	File "/var/lib/buildkite-agent/builds/bk-docker-ms75/bazel-org-repo-root/bazel-skylib/docs/private/stardoc_with_diff_test.bzl", line 107, column 11, in update_docs
		native.sh_binary(
Error: no native function or rule 'sh_binary'
Available attributes: action_listener, alias, available_xcodes, cc_binary, cc_import, cc_libc_top_alias, cc_library, cc_proto_library, cc_shared_library, cc_static_library, cc_test, cc_toolchain, cc_toolchain_alias, cc_toolchain_suite, config_feature_flag, config_setting, constraint_setting, constraint_value, environment, existing_rule, existing_rules, exports_files, extra_action, fdo_prefetch_hints, fdo_profile, filegroup, genquery, genrule, glob, java_binary, java_import, java_library, java_lite_proto_library, java_package_configuration, java_plugin, java_plugins_flag_alias, java_proto_library, java_runtime, java_test, java_toolchain, label_flag, label_setting, legacy_globals, memprof_profile, module_name, module_version, objc_import, objc_library, package, package_group, package_name, package_relative_label, platform, propeller_optimize, proto_lang_toolchain, proto_library, repo_name, repository_name, starlark_doc_extract, subpackages, test_suite, toolchain, toolchain_type, xcode_config, xcode_config_alias, xcode_version
(04:10:02) ERROR: package contains errors: docs
(04:10:02) ERROR: package contains errors: docs: Traceback (most recent call last):
	File "/var/lib/buildkite-agent/builds/bk-docker-ms75/bazel-org-repo-root/bazel-skylib/docs/BUILD", line 182, column 12, in <toplevel>
		update_docs(
	File "/var/lib/buildkite-agent/builds/bk-docker-ms75/bazel-org-repo-root/bazel-skylib/docs/private/stardoc_with_diff_test.bzl", line 107, column 11, in update_docs
		native.sh_binary(
Error: no native function or rule 'sh_binary'
``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/bazel-skylib
git reset 56b235e700ddd6a15b7d9fa1803fa7a84048471e  --hard
export USE_BAZEL_VERSION=00fdb673ba8276e83f1c821a7f93aab7038377e2
bazel build --incompatible_config_setting_private_default_visibility --incompatible_disallow_empty_glob //... @external_directory_tests//... @bazel_skylib_gazelle_plugin//... 
 ``` 
 CC Greenteam @meteorcloudy

**Comment by sgowroji** [comment]
CC @tetromino @comius

**Comment by tetromino** [comment]
Thanks. This was fixed in skylib at head by 6edf03b1954900034ca2d85d6bf381da6663a575, but we need to make a new skylib release containing this fix.

**Comment by deepalak56** [comment]
This issue has been fixed now, so we are closing this issue.
